lab2-rails/config/routes.rb
Pdish::Application.routes.draw do
  resources :data
	root :to => "data#index"

end

lab2-rails/app/models/datum.rb
class Datum < ActiveRecord::Base
  attr_accessible :number, :opacity
end

lab2-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

lab2-rails/app/controllers/data_controller.rb
class DataController < ApplicationController

	protect_from_forgery except: "create"
  
	def index
    @data = Datum.all
  end

  def create
    @datum = Datum.new()
		@datum.number = params[:number]
		@datum.opacity = params[:opacity]
	  @datum.save
  	
		respond_to do |format|
		format.html { redirect_to action: 'index'}
		end
  end

	def show
		@datum = Data.find(params[:id])
	end

  def destroy
    @datum = Datum.find(params[:id])
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url }
      format.json { head :no_content }
    end
  end
end

lab2-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

lab2-rails/app/helpers/data_helper.rb
module DataHelper
end

lab2-rails/app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :opacity %><br />
    <%= f.number_field :opacity %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lab2-rails/app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

lab2-rails/app/views/data/index.html.erb
<div class="hero-unit">
<h1>Listing Opacity logs</h1>
<a href= 'javascrip:document.location.reload();'> click to load new data</a>
</br>
</br>
<table border='1'>
	<tr>
    
    <th>Number</th>
		<th>Opacity</th>
    <th>Logged at</th>
    <th></th>
  </tr>


<% @data.each do |datum| %>
  <tr>
    <td><%= datum.number %></td>
    <td><%= datum.opacity.to_s + '%' %></td>
		<td><%= datum.created_at.strftime("%H:%M:%S  ") +  datum.created_at.strftime("%d %b. %Y")%></td>
    <td><%= link_to 'Delete', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

</div>

lab2-rails/app/views/data/new.html.erb
<h1>New datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

lab2-rails/app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Opacity:</b>
  <%= @datum.opacity %>
</p>

<p>
  <b>Number:</b>
  <%= @datum.number %>
</p>


<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>

lab2-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pdish</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>